// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// publish can be called by a notary-client to open a topic and publish data on it
type PublishRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PublishReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishReply) Reset()         { *m = PublishReply{} }
func (m *PublishReply) String() string { return proto.CompactTextString(m) }
func (*PublishReply) ProtoMessage()    {}
func (*PublishReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *PublishReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReply.Unmarshal(m, b)
}
func (m *PublishReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReply.Marshal(b, m, deterministic)
}
func (m *PublishReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReply.Merge(m, src)
}
func (m *PublishReply) XXX_Size() int {
	return xxx_messageInfo_PublishReply.Size(m)
}
func (m *PublishReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReply proto.InternalMessageInfo

func (m *PublishReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *PublishReply) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

// subscribe can be called by Scheduler to subscribe topic
type SubscribeRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type SubscribeReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Data                 []string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeReply) Reset()         { *m = SubscribeReply{} }
func (m *SubscribeReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeReply) ProtoMessage()    {}
func (*SubscribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *SubscribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReply.Unmarshal(m, b)
}
func (m *SubscribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReply.Marshal(b, m, deterministic)
}
func (m *SubscribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReply.Merge(m, src)
}
func (m *SubscribeReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeReply.Size(m)
}
func (m *SubscribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReply proto.InternalMessageInfo

func (m *SubscribeReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SubscribeReply) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *SubscribeReply) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

// stream
type PullDataRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullDataRequest) Reset()         { *m = PullDataRequest{} }
func (m *PullDataRequest) String() string { return proto.CompactTextString(m) }
func (*PullDataRequest) ProtoMessage()    {}
func (*PullDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *PullDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullDataRequest.Unmarshal(m, b)
}
func (m *PullDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullDataRequest.Marshal(b, m, deterministic)
}
func (m *PullDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullDataRequest.Merge(m, src)
}
func (m *PullDataRequest) XXX_Size() int {
	return xxx_messageInfo_PullDataRequest.Size(m)
}
func (m *PullDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullDataRequest proto.InternalMessageInfo

func (m *PullDataRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type PullDataReply struct {
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullDataReply) Reset()         { *m = PullDataReply{} }
func (m *PullDataReply) String() string { return proto.CompactTextString(m) }
func (*PullDataReply) ProtoMessage()    {}
func (*PullDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *PullDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullDataReply.Unmarshal(m, b)
}
func (m *PullDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullDataReply.Marshal(b, m, deterministic)
}
func (m *PullDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullDataReply.Merge(m, src)
}
func (m *PullDataReply) XXX_Size() int {
	return xxx_messageInfo_PullDataReply.Size(m)
}
func (m *PullDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PullDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_PullDataReply proto.InternalMessageInfo

func (m *PullDataReply) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Return published topics
type GetTopicsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsRequest) Reset()         { *m = GetTopicsRequest{} }
func (m *GetTopicsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTopicsRequest) ProtoMessage()    {}
func (*GetTopicsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *GetTopicsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsRequest.Unmarshal(m, b)
}
func (m *GetTopicsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsRequest.Marshal(b, m, deterministic)
}
func (m *GetTopicsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsRequest.Merge(m, src)
}
func (m *GetTopicsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTopicsRequest.Size(m)
}
func (m *GetTopicsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsRequest proto.InternalMessageInfo

type GetTopicsReply struct {
	Topics               []string `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTopicsReply) Reset()         { *m = GetTopicsReply{} }
func (m *GetTopicsReply) String() string { return proto.CompactTextString(m) }
func (*GetTopicsReply) ProtoMessage()    {}
func (*GetTopicsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *GetTopicsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTopicsReply.Unmarshal(m, b)
}
func (m *GetTopicsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTopicsReply.Marshal(b, m, deterministic)
}
func (m *GetTopicsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTopicsReply.Merge(m, src)
}
func (m *GetTopicsReply) XXX_Size() int {
	return xxx_messageInfo_GetTopicsReply.Size(m)
}
func (m *GetTopicsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTopicsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetTopicsReply proto.InternalMessageInfo

func (m *GetTopicsReply) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "service.PublishRequest")
	proto.RegisterType((*PublishReply)(nil), "service.PublishReply")
	proto.RegisterType((*SubscribeRequest)(nil), "service.SubscribeRequest")
	proto.RegisterType((*SubscribeReply)(nil), "service.SubscribeReply")
	proto.RegisterType((*PullDataRequest)(nil), "service.PullDataRequest")
	proto.RegisterType((*PullDataReply)(nil), "service.PullDataReply")
	proto.RegisterType((*GetTopicsRequest)(nil), "service.GetTopicsRequest")
	proto.RegisterType((*GetTopicsReply)(nil), "service.GetTopicsReply")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0xd7, 0x6d, 0x6e, 0xee, 0xb0, 0x75, 0x1c, 0x3a, 0x6b, 0x9f, 0x46, 0x7c, 0xb0, 0x4f,
	0x43, 0xf4, 0x6d, 0x82, 0x20, 0x08, 0xbe, 0x49, 0xe9, 0xfc, 0x02, 0x69, 0x8d, 0x58, 0x28, 0xb6,
	0x36, 0xa9, 0xd0, 0xaf, 0xe1, 0x27, 0x96, 0xa4, 0x59, 0x96, 0xce, 0x32, 0xf0, 0x2d, 0x97, 0xbb,
	0x7f, 0xee, 0x77, 0xff, 0x0b, 0xb8, 0x9c, 0x55, 0xdf, 0x59, 0xca, 0x56, 0x65, 0x55, 0x88, 0x02,
	0xa7, 0x3a, 0x24, 0x6b, 0xf0, 0xa2, 0x3a, 0xc9, 0x33, 0xfe, 0x11, 0xb3, 0xaf, 0x9a, 0x71, 0x81,
	0x67, 0x70, 0x24, 0x8a, 0x32, 0x4b, 0x7d, 0x67, 0xe9, 0x84, 0xb3, 0xb8, 0x0d, 0x10, 0x61, 0xfc,
	0x46, 0x05, 0xf5, 0x87, 0xea, 0x52, 0x9d, 0xc9, 0x1a, 0x4e, 0x8c, 0xb6, 0xcc, 0x1b, 0x5c, 0xc0,
	0x84, 0x0b, 0x2a, 0x6a, 0xae, 0xa4, 0xc7, 0xb1, 0x8e, 0xa4, 0x36, 0xfb, 0x7c, 0x2f, 0xb6, 0x5a,
	0x79, 0x26, 0x21, 0xcc, 0x37, 0x75, 0xc2, 0xd3, 0x2a, 0x4b, 0xd8, 0xc1, 0xce, 0x24, 0x02, 0xcf,
	0xaa, 0xfc, 0x67, 0x1f, 0xc3, 0x3d, 0x5a, 0x8e, 0x0c, 0xf7, 0x35, 0x9c, 0x46, 0x75, 0x9e, 0x3f,
	0x51, 0x41, 0x0f, 0xb7, 0xbe, 0x02, 0x77, 0x57, 0x28, 0x3b, 0xf7, 0xb9, 0x80, 0x30, 0x7f, 0x66,
	0xe2, 0x55, 0x0a, 0xb8, 0x7e, 0x8e, 0x84, 0xe0, 0x59, 0x77, 0x9a, 0x59, 0xbd, 0x29, 0x99, 0x25,
	0x89, 0x8e, 0x6e, 0x7f, 0x86, 0xe0, 0xbe, 0x14, 0x82, 0x56, 0xcd, 0xa6, 0xdd, 0x08, 0x3e, 0xc2,
	0xcc, 0xcc, 0x8b, 0x97, 0xab, 0xed, 0xde, 0xf6, 0xdd, 0x0a, 0x2e, 0xfa, 0x52, 0x65, 0xde, 0x90,
	0x01, 0xde, 0xc3, 0x54, 0x2f, 0x06, 0x77, 0x55, 0xdd, 0x35, 0x07, 0xe7, 0x7f, 0x13, 0xad, 0xf8,
	0x01, 0xc6, 0x72, 0x68, 0xf4, 0xad, 0x82, 0x8e, 0x59, 0xc1, 0xa2, 0x27, 0xa3, 0xb4, 0xa1, 0x73,
	0xe3, 0x48, 0x7e, 0x33, 0xbb, 0xc5, 0xbf, 0xef, 0x91, 0xc5, 0xdf, 0xb5, 0x8a, 0x0c, 0x92, 0x89,
	0xfa, 0xa4, 0x77, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xda, 0xbb, 0x12, 0xb5, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotaryServiceClient is the client API for NotaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotaryServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error)
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error)
	Pull(ctx context.Context, opts ...grpc.CallOption) (NotaryService_PullClient, error)
	GetTopics(ctx context.Context, in *GetTopicsRequest, opts ...grpc.CallOption) (*GetTopicsReply, error)
}

type notaryServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotaryServiceClient(cc *grpc.ClientConn) NotaryServiceClient {
	return &notaryServiceClient{cc}
}

func (c *notaryServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error) {
	out := new(SubscribeReply)
	err := c.cc.Invoke(ctx, "/service.NotaryService/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishReply, error) {
	out := new(PublishReply)
	err := c.cc.Invoke(ctx, "/service.NotaryService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notaryServiceClient) Pull(ctx context.Context, opts ...grpc.CallOption) (NotaryService_PullClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NotaryService_serviceDesc.Streams[0], "/service.NotaryService/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &notaryServicePullClient{stream}
	return x, nil
}

type NotaryService_PullClient interface {
	Send(*PullDataRequest) error
	Recv() (*PullDataReply, error)
	grpc.ClientStream
}

type notaryServicePullClient struct {
	grpc.ClientStream
}

func (x *notaryServicePullClient) Send(m *PullDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *notaryServicePullClient) Recv() (*PullDataReply, error) {
	m := new(PullDataReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *notaryServiceClient) GetTopics(ctx context.Context, in *GetTopicsRequest, opts ...grpc.CallOption) (*GetTopicsReply, error) {
	out := new(GetTopicsReply)
	err := c.cc.Invoke(ctx, "/service.NotaryService/GetTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotaryServiceServer is the server API for NotaryService service.
type NotaryServiceServer interface {
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error)
	Publish(context.Context, *PublishRequest) (*PublishReply, error)
	Pull(NotaryService_PullServer) error
	GetTopics(context.Context, *GetTopicsRequest) (*GetTopicsReply, error)
}

// UnimplementedNotaryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotaryServiceServer struct {
}

func (*UnimplementedNotaryServiceServer) Subscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedNotaryServiceServer) Publish(ctx context.Context, req *PublishRequest) (*PublishReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedNotaryServiceServer) Pull(srv NotaryService_PullServer) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (*UnimplementedNotaryServiceServer) GetTopics(ctx context.Context, req *GetTopicsRequest) (*GetTopicsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopics not implemented")
}

func RegisterNotaryServiceServer(s *grpc.Server, srv NotaryServiceServer) {
	s.RegisterService(&_NotaryService_serviceDesc, srv)
}

func _NotaryService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NotaryService/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaryService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NotaryService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotaryService_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NotaryServiceServer).Pull(&notaryServicePullServer{stream})
}

type NotaryService_PullServer interface {
	Send(*PullDataReply) error
	Recv() (*PullDataRequest, error)
	grpc.ServerStream
}

type notaryServicePullServer struct {
	grpc.ServerStream
}

func (x *notaryServicePullServer) Send(m *PullDataReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *notaryServicePullServer) Recv() (*PullDataRequest, error) {
	m := new(PullDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NotaryService_GetTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotaryServiceServer).GetTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NotaryService/GetTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotaryServiceServer).GetTopics(ctx, req.(*GetTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotaryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.NotaryService",
	HandlerType: (*NotaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _NotaryService_Subscribe_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _NotaryService_Publish_Handler,
		},
		{
			MethodName: "GetTopics",
			Handler:    _NotaryService_GetTopics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _NotaryService_Pull_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
